[package]
name = "servo-webgl-wgpu"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "webgl_wgpu"
path = "lib.rs"

[dependencies]
genet-compositor = { workspace = true }
servo-webgl-essl = { path = "../webgl-essl" }
wgpu = { version = "30", default-features = false, features = ["std", "parking_lot", "dx12", "metal", "vulkan", "wgsl"] }

[dev-dependencies]
pollster = "0.4"
